# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_files": "00_core.ipynb",
         "get_images_path": "00_core.ipynb",
         "notebook_json": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/img_checker/"

git_url = "https://github.com/{user}/img_checker/tree/{branch}/"

def custom_doc_links(name): return None
